##### Exploring the relationship between the modal age at deaths and the standard deviation above it #####
##### ---------------------------------------------------------------------------------------------- #####

## Following Cheung et al (2009), the goal of this project is to investigate the characteristics of the 
## longevity development in Switzerland. We assume that the increase in life expectancy which went along with
## the compression around the modal age of death (decreasing standard deviation) is increasingly driven by the
## shift of the modal age at death to higher ages. Looking at the variability measures could proof that hypothesis


# 0.1 load packages
library(HMDHFDplus)
library(MortalitySmooth)
library(MortHump)
library(tidyverse)
library(plyr)
# library(LifeTables)

# 0.2 working directory
setwd("C:/Users/Mathias/Documents/LongPop_Madrid/Secondment/Geneva/Compression of Mortality/Data and Code")

# 0.3 set passworts for HMDHFDplus
name.m <- "mathias.voigt4@uni-rostock.de"
name.f <- "m.voigt87@gmx.de"
pw.m <- "1320270854"
pw.f <- "43700"


females <- readHMDweb(CNTRY = "CHE", item = "fltper_1x1", username = name.m, password = pw.m)

# Smooth the mortality surface with P-Splines
fit <- Mort2Dsmooth(x = unique(females$Age), y = unique(females$Year), Z = matrix(females$mx, nrow = 111), 
                    method = 3, lambdas = c(.01,.01))
# plots
plot(fit)

# use the predict function to interpolate
females$mxs <- as.vector(predict(fit, type = "response"))

lt <- by(data = females$mxs, INDICES = females$Year, FUN = function(x){LT(Mx = x, mxsmooth = FALSE, 
                                                                          axsmooth = FALSE)})
## Compare the estimated values with observed
females$dxs <- unlist(lapply(lt, function(x){x$dx}))
females$exs <- unlist(lapply(lt, function(x){x$ex}))

plot(females$ex, females$exs)
head(females)

#femalesplus <- data.frame(Year = rep(unique(females$Year), each = 1100), x = rep(seq(0,109.9,0.1),length(unique(females$Year))))
#femalesplus$dxs <- predict(fit, newdata = data.frame(y = femalesplus$Year, x = femalesplus$x), type = "response")

### ---------
### For Males
### ---------

males <- readHMDweb(CNTRY = "CHE", item = "mltper_1x1", username = name.m, password = pw.m)
# Smooth the mortality surface with P-Splines
fit <- Mort2Dsmooth(x = unique(males$Age), y = unique(males$Year), Z = matrix(males$mx, nrow = 111), 
                    method = 3, lambdas = c(.01,.01))
plot(fit) # Spanish flu visible
# extract smoothed life table mx and calculate the rest of the indicators
males$mxs <- as.vector(predict(fit, type = "response"))
lt <- by(data = males$mxs, INDICES = males$Year, FUN = function(x){LT(Mx = x, mxsmooth = FALSE, axsmooth = FALSE)})
males$dxs <- unlist(lapply(lt, function(x){x$dx}))
males$exs <- unlist(lapply(lt, function(x){x$ex}))
plot(males$ex, males$exs)
head(males)

## test if outliers were generated by the Spanish flu (year 1918)

males.without <- males %>% filter(Year!=1918)
par(mfrow=c(1,2))
plot(males$ex, males$exs)
plot(males.without$ex, males.without$exs)
par(mfrow=c(1,1))

# looks like

# functions to compute e-dagger and sd+ (check this one though!)

# e-dagger - the average life expectancy losses due to death. 

# edagger <- function(lt){
#   
#   ed <- sum(lt$dxs / sum(lt$dxs) * lt$exs)
#   
#   return(ed)
#   
# }

 # sdplus <- function(lt){
 #  
 #  dx <- lt$dxs / sum(lt$dxs)
 #  x <- lt$Age
 #  m <- which.max(dx[x > 50]) + 51
 #  dx <- dx[m:length(dx)]
 #  x  <-  x[m:length(x)]
 #  mean <- sum(x * dx) / sum(dx)
 #  s <- sqrt(sum((x - m)^2 * dx) / sum(dx))
 # 
 #  return(s)
 # 
 # }
 # 
 # sdplus(females)
 
# 
# # apply both functions
# png("EPC/edagger.png", width = 30, height = 15, units = "cm", res = 600)
# par(mfrow = c(1,2), mar = c(3,4,3,1) + 0.1)
# plot(unique(females$Year), as.vector(by(data = females, INDICES = females$Year, FUN = edagger)), type = "l", xlab = "", ylab = expression(e^dagger), las = 1, main = "Swiss females", ylim = c(5,25))
# plot(unique(males$Year), as.vector(by(data = males, INDICES = males$Year, FUN = edagger)), type = "l", xlab = "", ylab = expression(e^dagger), las = 1, main = "Swiss males", ylim = c(5, 25))
# par(mfrow = c(1,1), mar = c(5,4,4,1) + 0.1)
# dev.off()
# 
# plot(unique(females$Year), as.vector(by(data = females, INDICES = females$Year, FUN = sdplus)), type = "l")




### ----------------- Experimenting !!!

#######################################################
### Standard deviation (Tuljarpurka & Edwards 2005) ###
#######################################################

# dx matrix - females
dx.fem <- tapply(X=females$dxs,
                 INDEX=list(Age=females$Age,
                            Year=females$Year),
                 FUN=sum)

# ex matrix - females
ex.fem <- tapply(X=females$exs,
                 INDEX=list(Age=females$Age,
                            Year=females$Year),
                 FUN=sum)

# To avoid the noise generated by infant mortality = suggested to start at age 10
 # Note: Margin=2 in matrix stands for columns

sd10.fem <- apply(X=dx.fem[-(1:11),], MARGIN = 2, FUN = function(x)
                  sd(c(x))) 
summary(sd10.fem) 
plot(x=unique(females$Year),sd10.fem)

# from age 0
sd.fem <- apply(X=dx.fem, MARGIN = 2, FUN = function(x)
                sd(c(x))) 
plot(x=unique(females$Year),sd.fem)

###########
### IQR ###
###########
IQR.fem <- apply(X=dx.fem, MARGIN = 2, FUN = function(x)
  IQR(x))
summary(IQR.fem)
plot(x=unique(females$Year),log(IQR.fem))

IQR.fem <- as.data.frame(IQR.fem) %>% mutate(Year=seq(1876,2014,1))
  
IQR.fem %>%  ggplot(aes(x=Year,y=IQR.fem)) +
  geom_point() +
  scale_y_continuous(name="IQR") +
  theme_bw()

################
### e-Dagger ###
################

### ---------------------------------------------------------
# formula based on: www.demogr.mpg.de/papers/technicalreports/tr-2012-002.pdf
### alternative: (http://pages.stern.nyu.edu/~dbackus/BCH/demography/ZhangVaupel_ageseparating_DR_09.pdf)

e.dagger.fun <- function(lt) {
  e.dagger <- sum(lt$dxs[lt$Age]*1/2*(lt$ex[lt$Age]+lt$ex[lt$Age+1]))
  return(e.dagger)
}

# creating a new data frame for easier plotting and handling the summarized values 
e.d.fem <- as.data.frame(unique(females$Year))
colnames(e.d.fem)[1] <- "Year"
e.d.fem <- e.d.fem %>% mutate(edagger=NA)
# for now with a for loop
for (i in 1876:2014) {
  e.d.fem$edagger[e.d.fem$Year==i] <- e.dagger.fun(subset(females,Year==i & Age<95))
}

## E-dagger plot (reasonable)
e.d.fem %>% ggplot(aes(x=Year, y=edagger))+ 
  geom_point() +
  scale_y_continuous(name = "e+ in years") +
  theme_bw()


# dplyr version (to be finished)

# EDAG <- females %>% group_by(Year) %>% summarise(edagger = sum(dxs[Age]*1/2*(ex[Age]+ex[Age+1])))


#######################
### Keyfitz entropy ###
#######################

e.d.fem$ex <- females$exs[females$Age==0]
e.d.fem$H <- e.d.fem$edagger/e.d.fem$ex

e.d.fem %>% ggplot(aes(x=Year, y=H))+ 
  geom_point() +
  scale_y_continuous(name = "Keyfitz' LT Entropy") +
  theme_bw()



##########################################
### From Modal Age at death to the SD+ ###
##########################################

## Calculate the mode over the the dx after age 5 (based on Canudas-Romo 2010)
## https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3000019/) - Appendix A (formula A2)

## Function to calculate the mode (after age 5) 
#  x is the age with the highest number of deaths in the life table at the time
MDA.fun <- function(lt) {
  x <- lt$Age[which.max(lt$dxs)]
  M <- x + ((lt$dxs[x]-lt$dxs[x-1])/(lt$dxs[x]-lt$dxs[x-1])+(lt$dxs[x]-lt$dxs[x+1]))
  return(M)
}


# test <- MDA.fun(subset(females,Year==1960 & Age>5))
# test 
# Seems to work fine with different years

# for each year - give me the age after 5 where the most deaths occur
# the not so elegant way for now:
mdsd.fem <- as.data.frame(unique(females$Year))
colnames(mdsd.fem)[1] <- "Year"
mdsd.fem <- mdsd.fem %>% mutate(M=NA)

for (j in 1876:2014) {
  mdsd.fem$M[mdsd.fem$Year==j] <- MDA.fun(subset(females, Year==j & Age>5))
}

summary(mdsd.fem)

### Plot

mdsd.fem %>% ggplot(aes(x=Year, y=M)) +
              geom_point() +
              scale_x_continuous(name="year") + 
              scale_y_continuous(name="modal age at death (after age 5)") +
              theme_bw()



## dplyr - version Calculate the modal age at death after age 5 by year
# fem.test <- females %>% filter(Age>5) %>% group_by(Year) %>% 
#   dplyr::summarise(MDA = MDA.fun(lt))







## --------------------------------------------------------------------------- ##
## general mode
# Mode <- function(x) {
#   ux <- unique(x)
#   ux[which.max(tabulate(match(x, ux)))]
# }

# Kannisto (2001) - M(t) = x + (d(x,t)-d(x-1,t))/(2d(x,t)-d(x-1,t)-d(x+1,t))
## --------------------------------------------------------------------------- ##








###### function to fit a Gompertz model for adult mortality

# DENSITY FUNCTION Gompertz
# NOTE: x=x, shape=a, scale=b
x <- seq(5,35,1)
dwei <- function(x, a, b){
  part.1   <- (a/b)
  part.2   <- (x/b)^(a-1)
  part.3   <- exp(-(x/b)^a)
  f.x.a.b  <- part.1*part.2*part.3
  return(f.x.a.b)
}





